/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface JesusCryptUtilsInterface extends utils.Interface {
  functions: {
    "CHAINLINK_BNB_USDT()": FunctionFragment;
    "getLatestBNBPrice()": FunctionFragment;
    "toDateTime(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "CHAINLINK_BNB_USDT"
      | "getLatestBNBPrice"
      | "toDateTime"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "CHAINLINK_BNB_USDT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestBNBPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "toDateTime",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "CHAINLINK_BNB_USDT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestBNBPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "toDateTime", data: BytesLike): Result;

  events: {};
}

export interface JesusCryptUtils extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: JesusCryptUtilsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    CHAINLINK_BNB_USDT(overrides?: CallOverrides): Promise<[string]>;

    getLatestBNBPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    toDateTime(
      _timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;
  };

  CHAINLINK_BNB_USDT(overrides?: CallOverrides): Promise<string>;

  getLatestBNBPrice(overrides?: CallOverrides): Promise<BigNumber>;

  toDateTime(
    _timestamp: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  callStatic: {
    CHAINLINK_BNB_USDT(overrides?: CallOverrides): Promise<string>;

    getLatestBNBPrice(overrides?: CallOverrides): Promise<BigNumber>;

    toDateTime(
      _timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;
  };

  filters: {};

  estimateGas: {
    CHAINLINK_BNB_USDT(overrides?: CallOverrides): Promise<BigNumber>;

    getLatestBNBPrice(overrides?: CallOverrides): Promise<BigNumber>;

    toDateTime(
      _timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    CHAINLINK_BNB_USDT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLatestBNBPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    toDateTime(
      _timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
